version: "3.9"  
services:
  api:
    container_name: flight-api              
    build:
      context: ./Server                    
      dockerfile: Dockerfile               
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"  
      ConnectionStrings__Default: "Data Source=/app/Data/app.db" 
    ports:
      - "8080:8080"                          
    volumes:
      - api_data:/app/Data                   
    networks:
      - flightnet                            

  web:
    container_name: flight-web               
    build:
      context: ./Client                    
      dockerfile: Dockerfile                 
    depends_on:
      - api                                 
    ports:
      - "8081:80"                           
    networks:
      - flightnet                            

networks:
  flightnet:                                 

volumes:
  api_data:                                
