version: "3.9"

services:
  flightboard-api:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: flightboard-api
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Server/app.db:/app/app.db 
    depends_on:
      - sqlite-db

  sqlite-db:
    image: nouchka/sqlite3
    container_name: flightboard-sqlite
    stdin_open: true
    tty: true
    volumes:
      - ./Server:/root/db
